version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
    - "16686:16686" # Web UI
    - "14250:14250" # gRPC for Jaeger-to-Jaeger communication
    - "4317:4317" # OTLP gRPC receiver
    - "4318:4318" # OTLP HTTP receiver
    environment:
    - COLLECTOR_OTLP_ENABLED=true


  otel-collector:
    image: otel/opentelemetry-collector:0.88.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4319:4317" # OTLP gRPC receiver
      - "4320:4318" # OTLP HTTP receiver
    depends_on:
      - jaeger

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: techbankRootPsw
    restart: always
    volumes:
      - mysql_data_container:/var/lib/mysql

volumes:
  mysql_data_container:
